### ISSUE TITLE
Metadata mapping targets seem off for migration

### ISSUE THREAD

**Issue by vantuyls** [osulp/dspace2hydra#111]
http://ir-staging.library.oregonstate.edu/concern/etds/t722h8817/edit?locale=en

Issues:
- [ ] no abstract
- [ ] dates not mapped
- [ ] resource type not mapped

**Comment by revgum** [comment]
should be invalid after we merge SA PRs and deploy to staging server

**Comment by revgum** [comment]
was related to SA work for metadata
