### ISSUE TITLE
license / copyright mapping

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#112]
checking data.copyright
- if not set, no known copyright
- if before 1923 then no copyright
- if after 1923 then rights reserved

**Comment by zhang4952** [comment]
For ETD: use 'graduation year'
For OA and others: use 'dc.date.issued'

**Comment by mwillihooper** [comment]
Here you go: https://docs.google.com/spreadsheets/d/1_Mj90z_abGrmn_xz-fnM8mF_NWGDv9br7kNIs6FfQWw/edit?usp=sharing

Let me know if there are any instances I haven't identified! As far as I know, what we're doing here is new b/c rightsstatements are fairly new, so if any copyright folks at UO or other collaborators want to use this or work with me on it, I'm happy to share.

**Comment by revgum** [comment]
closed in #125
