### ISSUE TITLE
Automate DSpace exporting

### ISSUE THREAD

**Issue by zhang4952** [osulp/dspace2hydra#115]
Write a Ruby script to automate exporting DSpace bags
- read file with a list of items to export: collection_handle,item_handle
- run curate to export bags in zip
- scp bags to destination (e.g., ir-staging and creating directory with collection handle)
- unzip bags

**Comment by revgum** [comment]
Need:
Prior to running the dspace2hydra script we need to know what configuration file to use. At runtime the only thing we'll really know is the filename of the BAG. Ideally we would have a list of ITEM IDs (BAG filenames start with this) and the worktype configuration to use.

**Comment by zhang4952** [comment]
The spreadsheet will also include collection column and uploaded to Google drive: https://drive.google.com/open?id=0Bxlj1p4QYIzjUzdDc3pqUkZjQjA

**Comment by zhang4952** [comment]
!!! The item-wt mapping list MUST be re-generated for live (non-stable) collections (e.g., OA, ETD, CUE, URSA) before migration and after DSpace freeze.
