### ISSUE TITLE
update mapping of resource types for thesis/dissertation

### ISSUE THREAD

**Issue by vantuyls** [osulp/dspace2hydra#131]
resource types in hyrax map dspace resource type to hyrax resource type based on dc.degree.level and dc.type

for dc.type = thesis/dissertation, if degree level = doctoral, resource type is Dissertation
for dc.type = thesis/dissertation, if degree level = masters, resource type is Graduate Thesis

**Comment by vantuyls** [comment]
see map: https://docs.google.com/spreadsheets/d/1x_P7WszhOoIKs-vfGrP5j9ichlWrJaa82ZnrHM8Z8no/edit#gid=311701783

**Comment by revgum** [comment]
I think you intended "Masters Thesis" as the resource type, to match what is in the MAP, can you confirm?
