### ISSUE TITLE
academic unit lookup and mapping

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#134]
custom node mapping configuration to lookup and mapping the academic unit for an ITEM / Community

**Comment by vantuyls** [comment]
Mapping from each Community and Collection to Academic Units: https://docs.google.com/spreadsheets/d/1Z_G-LO65NYf5BqkMH0koLzG5DoZ8KD3yAapViWCxiJw/edit#gid=0

**Comment by revgum** [comment]
@vantuyls So, for any ETD would we use @mlv611 lookup to determine the academic unit, and then for any work that isn't an ETD we would use the `College Affiliation` or `Department Affiliation` in the spreadsheet link you attached? 

Also, were is the lookup to find the appropriate URI for each of these College/Department Affiliations?

**Comment by vantuyls** [comment]
@revgum yeah, for every ETD there is an academic unit (more or less). anything else will use the affiliations in the spreadsheet. 

Note: there is a third column "Other Affiliation" that maps to URIs in http://opaquenamespace.org/ns/subject

**Comment by mlv611** [comment]
https://docs.google.com/spreadsheets/d/198w5cxHfd6-s61_kUM3FaXJpABKByMrOlXs7s8yEJ_o/edit#gid=1455299425

https://docs.google.com/spreadsheets/d/1JFYzBBO73F2CdiMdJrtfIfiK_aU7ZAQ54G5Ehb30Y_o/edit#gid=0

Here are the two spreadsheets with the department filled in.  If there is no department filled in, then there is an issue with the item, such as it is not there or it is a bachelors degree.

**Comment by vantuyls** [comment]
http://opaquenamespace.org/ns/osuAcademicUnits
