### ISSUE TITLE
prevent a couple collections from being migrated

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#158]
Collections that aren't ready for migration have been moved to `on_hold.stable.collections.csv` on the production server.

1957/12161
1957/12309

**Comment by revgum** [comment]
The bags for these items are found in `on_hold_bags`

**Comment by zhang4952** [comment]
- items in SCARC on_hold collections are moved from stable.collections.csv to on_hold.stable.collections.csv
- items in collections with mixed WTs are moved from stable.collections.csv to mixed_type.stable.collections.csv
