### ISSUE TITLE
Zip files not found

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#160]
```
item.item_id,item.owning_collection,collection_handle,admin_set_name,bag_file,item_handle,resource_type,bag_style_handle
17678,268,1957/12945,Administrative Report or Publication,ITEM@1957-14169.zip,1957/14169,2,1957-14169
18393,232,1957/12080,Administrative Report or Publication,ITEM@1957-14878.zip,1957/14878,2,1957-14878
41214,345,1957/14946,Default,ITEM@1957-35861.zip,1957/35861,2,1957-35861
37116,54,1957/1723,Graduate Thesis or Dissertation,ITEM@1957-31858.zip,1957/31858,2,1957-31858
37054,54,1957/1723,Graduate Thesis or Dissertation,ITEM@1957-31859.zip,1957/31859,2,1957-31859
7560,90,1957/3905,Administrative Report or Publication,ITEM@1957-5831.zip,1957/5831,2,1957-5831
63965,668,1957/56897,Conference Proceedings or Journal,ITEM@1957-57251.zip,1957/57251,2,1957-57251
2775,18,1957/93,Default,ITEM@1957-1873.zip,1957/1873,2,1957-1873
```
1857,18,1957/93,Default,ITEM@1957-1640.zip,1957/1640,2,1957-1640
2004,18,1957/93,Default,ITEM@1957-1961.zip,1957/1961,2,1957-1961
2390,18,1957/93,Default,ITEM@1957-2068.zip,1957/2068,2,1957-2068
3529,18,1957/93,Default,ITEM@1957-2837.zip,1957/2837,2,1957-2837
2012,18,1957/93,Default,ITEM@1957-1972.zip,1957/1972,2,1957-1972
```
3412,18,1957/93,Default,ITEM@1957-2683.zip,1957/2683,2,1957-2683
2008,18,1957/93,Default,ITEM@1957-1966.zip,1957/1966,2,1957-1966
2008,18,1957/93,Default,ITEM@1957-1968.zip,1957/1968,2,1957-1968
2516,18,1957/93,Default,ITEM@1957-2130.zip,1957/2130,2,1957-2130
3479,18,1957/93,Default,ITEM@1957-2797.zip,1957/2797,2,1957-2797
000,111,1957/18402,Graduate Project,ITEM@1957-49886.zip,1957/49886,2,1957-46886


Have been removed from the stable.collections.csv

**Comment by zhang4952** [comment]
zip files left in bags after stable.collection.csv is empty
000,111,1957/18402,Graduate Project,ITEM@1957-49886.zip,1957/49886,2,1957-46886
51800,169,1957/9973,Default,ITEM@1957-30517.1..zip,1957/30517.1,2,1957-30517.1
54858,639,1957/48655,Technical Report,ITEM@1957-48660.zip,1957/48660,2,1957-48660
54857,639,1957/48655,Technical Report,ITEM@1957-48659.zip,1957/48659,2,1957-48659
54856,639,1957/48655,Technical Report,ITEM@1957-48658.zip,1957/48658,2,1957-48658
54855,639,1957/48655,Technical Report,ITEM@1957-48657.zip,1957/48657,2,1957-48657
54852,639,1957/48655,Technical Report,ITEM@1957-48656.zip,1957/48656,2,1957-48656
44694,507,1957/28635,Default,ITEM@1957-35123.1.zip,1957/35123.1,2,1957-35123.1
25496,11,1957/29,Default,ITEM@1957-21666.1.zip,1957/21666.1,2,1957-21666.1
69000,386,1957/16561,,ITEM@1957-61472.zip,1957/61472,2,1957-61472
65494,386,1957/16561,,ITEM@1957-58538.zip,1957/58538,2,1957-58538
64471,386,1957/16561,,ITEM@1957-57792.zip,1957/57792,2,1957-57792
48186,386,1957/16561,,ITEM@1957-42454.zip,1957/42454,2,1957-42454
23354,295,1957/13727,,ITEM@1957-19586.zip,1957/19586,2,1957-19586
20493,386,1957/16561,,ITEM@1957-16565.zip,1957/16565,2,1957-16565
19870,295,1957/13727,,ITEM@1957-16236.zip,1957/16236,2,1957-16236
17221,295,1957/13727,,ITEM@1957-13761.zip,1957/13761,2,1957-13761
17202,295,1957/13727,,ITEM@1957-13735.zip,1957/13735,2,1957-13735
17195,295,1957/13727,,ITEM@1957-13734.zip,1957/13734,2,1957-13734

**Comment by zhang4952** [comment]
Items with missing zips in on_hold.etd.csv
40159,17,1957/89,Graduate Thesis or Dissertation,ITEM@1957-35134.zip,1957/35134,2,1957-35134

**Comment by zhang4952** [comment]
Replace by #226
