### ISSUE TITLE
Bag contains very large files requiring better handling for migration

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#171]
A list of bags that have very large files which need to be handled in a different way than just the automated script.. these file uploads timeout.

The bag files and these rows have been added to the `on_hold_bags` directory and `on_hold.stable.collections.csv` file.

```
item.item_id,item.owning_collection,collection_handle,admin_set_name,bag_file,item_handle,resource_type,bag_style_handle
65904,681,1957/58895,Technical Report,ITEM@1957-58909.zip,1957/58909,2,1957-58909
65897,681,1957/58895,Technical Report,ITEM@1957-58905.zip,1957/58905,2,1957-58905
65896,681,1957/58895,Technical Report,ITEM@1957-58903.zip,1957/58903,2,1957-58903
65905,681,1957/58895,Technical Report,ITEM@1957-58908.zip,1957/58908,2,1957-58908
65907,681,1957/58895,Technical Report,ITEM@1957-58912.zip,1957/58912,2,1957-58912
65908,681,1957/58895,Technical Report,ITEM@1957-58913.zip,1957/58913,2,1957-58913
65909,681,1957/58895,Technical Report,ITEM@1957-58914.zip,1957/58914,2,1957-58914
25703,158,1957/9112,Default,ITEM@1957-21680.zip,1957/21680,2,1957-21680
26867,158,1957/9112,Default,ITEM@1957-22799.zip,1957/22799,2,1957-22799
14470,158,1957/9112,Default,ITEM@1957-11454.zip,1957/11454,2,1957-11454
14187,158,1957/9112,Default,ITEM@1957-11284.zip,1957/11284,2,1957-11284
49895,158,1957/9112,Default,ITEM@1957-44258.zip,1957/44258,2,1957-44258
1437,18,1957/93,Default,ITEM@1957-809.zip,1957/809,2,1957-809
3548,18,1957/93,Default,ITEM@1957-2536.zip,1957/2536,2,1957-2536
3357,18,1957/93,Default,ITEM@1957-2649.zip,1957/2649,2,1957-2649
61772,18,1957/93,Default,ITEM@1957-55313.zip,1957/55313,2,1957-55313

```

**Comment by zhang4952** [comment]
on_hold.non.stable.collection.csv
61107,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-54641.zip,1957/54641,2,1957-54641
61680,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-55255.zip,1957/55255,2,1957-55255
39840,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-35101.zip,1957/35101,2,1957-35101
59390,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-55927.zip,1957/55927,2,1957-55927
65865,459,1957/21372,Undergraduate Thesis or Project,ITEM@1957-58874.zip,1957/58874,2,1957-58874
40520,41,1957/1339,,ITEM@1957-35406.zip,1957/35406,2,1957-35406
34127,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-29430.zip,1957/29430,2,1957-29430
40624,8,1957/22,Default,ITEM@1957-35522.zip,1957/35522,2,1957-35522
39031,8,1957/22,Default,ITEM@1957-33982.zip,1957/33982,2,1957-33982
38829,8,1957/22,Default,ITEM@1957-33732.zip,1957/33732,2,1957-33732
38815,8,1957/22,Default,ITEM@1957-33731.zip,1957/33731,2,1957-33731
44931,414,1957/18339,Undergraduate Thesis or Project,ITEM@1957-38906.zip,1957/38906,2,1957-38906

**Comment by zhang4952** [comment]
on_hold.etd.csv

14973,17,1957/89,Graduate Thesis or Dissertation,ITEM@1957-11752.zip,1957/11752,2,1957-11752
14781,17,1957/89,Graduate Thesis or Dissertation,ITEM@1957-11592.zip,1957/11592,2,1957-11592
12507,17,1957/89,Graduate Thesis or Dissertation,ITEM@1957-9696.zip,1957/9696,2,1957-9696
24479,17,1957/89,Graduate Thesis or Dissertation,ITEM@1957-20612.zip,1957/20612,2,1957-20612

**Comment by zhang4952** [comment]
Done
