### ISSUE TITLE
configuration qualifier errors

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#177]
After migration I ran a quick analysis on the error files to find failed migrations due to invalid/missing configuration for mapping metadata. 

**It's possible that a few of these have been addressed already, but we need to confirm and/or update the configurations for each of these.**

 - [ ] administrative_report_or_publication :  Missing description.other qualifier
 - [ ] administrative_report_or_publication :  Missing description.printable qualifier
 - [ ] administrative_report_or_publication :  Missing description.uri qualifier
 - [ ] administrative_report_or_publication :  Missing keyword.other qualifier
 - [ ] administrative_report_or_publication :  Missing related_url.ispartof qualifier
 - [ ] administrative_report_or_publication :  Missing related_url.reportsandpublications qualifier
 - [ ] administrative_report_or_publication :  Missing replaces.govdoc qualifier
 - [ ] article :  Missing replaces.issn qualifier
 - [ ] article :  Missing replaces.orcid qualifier
 - [ ] conference_proceedings_or_journal :  Missing description.other qualifier
 - [ ] conference_proceedings_or_journal :  Missing editor.advisor qualifier
 - [ ] conference_proceedings_or_journal :  Missing editor.author qualifier
 - [ ] conference_proceedings_or_journal :  Missing keyword.lcc qualifier
 - [ ] conference_proceedings_or_journal :  Missing keyword.other qualifier
 - [ ] conference_proceedings_or_journal :  Missing related_url.reportsandpublications qualifier
 - [ ] dataset :  Missing keyword.other qualifier
 - [ ] dataset :  Missing replaces.other qualifier
 - [ ] default :  Missing description.disclaimer qualifier
 - [ ] default :  Missing description.other qualifier
 - [ ] default :  Missing description.printable qualifier
 - [ ] default :  Missing keyword.cab qualifier
 - [ ] default :  Missing keyword.other qualifier
 - [ ] default :  Missing location.spatialcities qualifier
 - [ ] default :  Missing location.spatialcounties qualifier
 - [ ] default :  Missing location.spatial-ecoregion qualifier
 - [ ] default :  Missing location.spatialecoregion qualifier
 - [ ] default :  Missing location.spatialoregonplanbasins qualifier
 - [ ] default :  Missing location.spatial qualifier
 - [ ] default :  Missing location.spatialstates qualifier
 - [ ] default :  Missing location.spatialwatershedcouncils qualifier
 - [ ] default :  Missing location.temporal qualifier
 - [ ] default :  Missing related_url.photosandvideos qualifier
 - [ ] default :  Missing related_url.reportsandpublications qualifier
 - [ ] default :  Missing related_url.statisticsanddata qualifier
 - [ ] default :  Missing replaces.govdoc qualifier
 - [ ] default :  Missing replaces.orcid qualifier
 - [ ] default :  Missing replaces.other qualifier
 - [ ] graduate_thesis_or_dissertation :  Missing contributor.other qualifier
 - [ ] graduate_thesis_or_dissertation :  Missing description.graduationdate qualifier
 - [ ] graduate_thesis_or_dissertation :  Missing description.other qualifier
 - [ ] graduate_thesis_or_dissertation :  Missing description.uri qualifier
 - [ ] technical_report :  Missing description.disclaimer qualifier
 - [ ] technical_report :  Missing description.other qualifier
 - [ ] technical_report :  Missing keyword.other qualifier
 - [ ] technical_report :  Missing related_url.ispartof qualifier
 - [ ] technical_report :  Missing related_url.photosandvideos qualifier
 - [ ] technical_report :  Missing related_url.reportsandpublications qualifier
 - [ ] technical_report :  Missing replaces.orcid qualifier
 - [ ] technical_report :  Missing replaces.other qualifier
 - [ ] undergraduate_thesis_or_project :  Missing description.graduationdate qualifier
 - [ ] undergraduate_thesis_or_project :  Missing description.other qualifier

**Comment by zhang4952** [comment]
The initial crosswalk for missing qualifiers is here: https://docs.google.com/a/oregonstate.edu/spreadsheets/d/1evaVA9kukm8hhID8WP7mu8XkqdYsf-4oN3lSQb-n2js/edit?usp=sharing.

**Comment by zhang4952** [comment]
@vantuyls @wickr for comments

**Comment by zhang4952** [comment]
The crosswalk for missing element and qualifier has been finalized.
