### ISSUE TITLE
The value of date_issued only has year, the system expects at least year, month in YYYY-MM format

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#180]
There are several failed migrations due to metadata having an invalid date with regard to `mapping/license.rb:29`.

**Comment by zhang4952** [comment]
@revgum: This is probably because date_issued only has year, but no month. 'System' you mean app model in Hyrax, correct? Can we bypass it?

**Comment by zhang4952** [comment]
fix by PR#216
