### ISSUE TITLE
processing failed migrations dynamically

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#183]
- [x] (failed_migrations.directories) generate a list of all of the directories beneath `processed/ready_for_troubleshooting/*/*/*` to point at each of the ITEM directories
- [x] (failed_migrations) generate a list of all of the ITEMs that have FATAL errors and did not migrate
- [x] (failed_migrations.configuration_types) generate a list of the type of configuration that each ITEM should be run with

## Reprocess Failed Migration Script
- [ ] (argument) ITEM_ID
- [ ] Find the appropriate line in `failed_migrations.directories` file as `failed_item_directory`
  - [ ] Split the line on `\` and use the 4th element to find its `configuration_type_subdirectory`
  - [ ] Find the appropriate line in `failed_migrations.configuration_types` related to the `configuration_type_subdirectory`, and split the line on `,` to use the 2nd element as the `configuration_filename`
  - [ ] Run `dspace2hydra -d {failed_item_directory} -c config/{configuration_filename}` to reprocess the ITEM with the appropriate configuration file.

## Reprocess Failed Migration Worflow
- [ ] Identify (error log file grep, cut, etc) ITEMs that can be fixed in bulk, feed a list of ITEMs to a the reprocess failed migration script to run dspace2hydra on it

**Comment by zhang4952** [comment]
include #194

**Comment by revgum** [comment]
no longer valid, these steps have been processed and we're currently working on data fixes
