### ISSUE TITLE
cross examine DSpace and SA to verify items are all migrated

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#185]
Extract the handles from SA solr
Generate a list of the handles stored in DSpace

If new items are ingested in DSpace during the migration, we should have a short list of ITEMs that need to be migrated.

**Comment by zhang4952** [comment]
include #172

**Comment by zhang4952** [comment]
Include following tasks:
1. bags not exported from DSpace for some reasons: #226 
2. bags not ingested to Hyrax for some reasons: #172 
3. items ingested to DSpace after Jun 23, 2017: #227 
4. big bags: #171

**Comment by zhang4952** [comment]
All done
