### ISSUE TITLE
DSpace metadata change, then export

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#188]
ITEM@1957-54812 | change bibtex.address to dc.subject in DSpace and export again
ITEM@1957-50652 | change bibtex.address to dc.description in DSpace and export again

**Comment by zhang4952** [comment]
The four items are changed, exported, and copied to saapp1 for bibtex.address, see https://docs.google.com/spreadsheets/d/1evaVA9kukm8hhID8WP7mu8XkqdYsf-4oN3lSQb-n2js/edit#gid=0:
1957/50652
1957/60567
1957/56117
1957/54812
