### ISSUE TITLE
degree name 

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#19]
146 were not labelled with a degree name, should these be manually updated in DSpace before we export them?

@vantuyls is creating a Google spreadsheet to track the updating of each of these

**Comment by zhang4952** [comment]
Is the dataset ready to be imported back to DSpace?

**Comment by mlv611** [comment]
@zhang4952 It is ready to go.

**Comment by zhang4952** [comment]
@mlv611 : Several items in the Google doc have un-readable characters in author and title, could you correct them?

**Comment by zhang4952** [comment]
Missing or in-complete dc.degree.name in DSpace have been corrected based on the Goodle doc
