### ISSUE TITLE
identify files which should not be loaded into hydra

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#2]
using a configurable mapping, prevent unnecessary files from being uploaded into the hydra instance

see #1

**Comment by zhang4952** [comment]
We have decided to migrate all the files in the ORIGINAL folder in the DSpace export bags, but not other folders.

**Comment by zhang4952** [comment]
The code should have been merged, but I will let josh to confirm it.

**Comment by revgum** [comment]
merged in previous PR
