### ISSUE TITLE
Mismatch - dissertation attached to incorrect description

### ISSUE THREAD

**Issue by simholt** [osulp/dspace2hydra#238]
http://ir.library.oregonstate.edu/concern/defaults/mp48sj47p

Item description is attached to a dissertation instead of "Effect of moisture on the compressive strength of plywood and laminated wood."

Maybe related? -- > I looked up the author of the dissertation and found this same item is duplicated in the system eight times. I will create a new issue for that.

**Comment by simholt** [comment]
Okay, this can be deleted but not by me (that I can see). Hui, can you delete it?

**Comment by zhang4952** [comment]
Deleted
