### ISSUE TITLE
Dissertation duplicated 8 times

### ISSUE THREAD

**Issue by simholt** [osulp/dspace2hydra#239]
These are all the same:

http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/pz50h093q
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/qn59q769s 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/m326m599n 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/70795d03c 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/3j3336647 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9s161b20j 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/zw12z930j 
http://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/9019s695d

**Comment by revgum** [comment]
completed
