### ISSUE TITLE
Attach missing files to fileset and work

### ISSUE THREAD

**Issue by zhang4952** [osulp/dspace2hydra#240]
Josh tracked down a problem, and fixed, files that were failing because we had a pretty old version of `ffmpeg` on the server that was failing because of an old version of a codec being used.

- [x] Reingesting ~1500 files on FileSets that were created but didn’t get files attached.. variety of problems (`ffmpeg`, `ImageMagick`, and likely some system load related). I’ll have a couple hundred queued tonight, and will fire off the rest tomorrow morning… 

- [x] Next up, 611 FileSets that are “children” works, which is a slightly more

**Comment by revgum** [comment]
finished
