### ISSUE TITLE
Make sure everything in DSpace has been migrated

### ISSUE THREAD

**Issue by zhang4952** [osulp/dspace2hydra#242]
- [x] Create a list of all handles in DSpace with collection and status

- [x] Search and find out legitimate DSpace items missing in Hyrax

**Comment by simholt** [comment]
Corvallis Campus Schedule of Classes -- anything before 2017 is still in DSpace. The other campuses are there, but not Corvallis.

Example: 
http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/51857

**Comment by zhang4952** [comment]
Here is the items need to be ingested to SA but not yet, mostly likely due to missing the collection.
[dspace_items_not_ingested.txt](https://github.com/osulp/dspace2hydra/files/1520135/dspace_items_not_ingested.txt)

**Comment by simholt** [comment]
This thesis -- which looks like it is on your list already.

http://dspace-ir.library.oregonstate.edu/xmlui/handle/1957/61713

**Comment by zhang4952** [comment]
close when #243 complete

**Comment by zhang4952** [comment]
@simholt : both items have been ingested to Hyrax. I will confirm you when I think everything in that list is ingested.

**Comment by zhang4952** [comment]
Complete!
