### ISSUE TITLE
identify metadata that should not be loaded into hydra

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#3]
using a configuration, explicitly map metadata from dspace to field names in the hydra instance.

see #1

**Comment by mlv611** [comment]
This is one for @mwillihooper

**Comment by mwillihooper** [comment]
@revgum - could we briefly chat about what's still needed here?

**Comment by revgum** [comment]
@mlv611 and @mwillihooper this is actually a much more broad issue, no worries about either of you focusing on this one specifically.

**Comment by revgum** [comment]
The ability to explicitly ignore mapping some metadata is now capable for any of the nodes using a `add_data_to_migration: never` configuration.
