### ISSUE TITLE
Invalid rights defined in DSpace and need updates

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#38]
Each currently has 'An error occurred on the license name.' and need to have their rights updated before migration.

http://hdl.handle.net/1957/55586
http://hdl.handle.net/1957/55701
http://hdl.handle.net/1957/55768
http://hdl.handle.net/1957/55759
http://hdl.handle.net/1957/55776
http://hdl.handle.net/1957/56217
http://hdl.handle.net/1957/44452
http://hdl.handle.net/1957/49160
http://hdl.handle.net/1957/59717

**Comment by mwillihooper** [comment]
http://hdl.handle.net/1957/55586 - emailed author
http://hdl.handle.net/1957/55701 - emailed author

**Comment by mwillihooper** [comment]
http://hdl.handle.net/1957/55768 - from the dc.rights field, looks like this author tried to apply a CC BY-ND 3.0 license (attribution, no derivs). @revgum, let me know if you want me to go in and muck with trying to fix the fields, or if there is someone more skilled with that.

**Comment by mwillihooper** [comment]
Talked to @vantuyls : I'll fix the rights statements for the honors theses as I can and document here what's fixed. For ETDs, I will go through Richard's department to have them fixed.

**Comment by mwillihooper** [comment]
I've fixed all the records that aren't ETDs ([details in this spreadsheet](https://docs.google.com/a/oregonstate.edu/spreadsheets/d/1NFeoAQD1WsofV4TDOknVNglVSsfOfQxABtq3vx4mSdM/edit?usp=sharing)). For the ETDs, I emailed all but one of the authors (couldn't find an email for the other author). Steve and I are going to work with Richard's dept. to resolve the five theses, since they're cataloged.

**Comment by mwillihooper** [comment]
Emailed Richard today to see if his dept. could help us fix these five remaining ETDs:

http://hdl.handle.net/1957/55701: Author selected CC BY-NC
http://hdl.handle.net/1957/55776: Couldn’t contact author — apply “all rights reserved”
http://hdl.handle.net/1957/56217: Author selected CC BY
http://hdl.handle.net/1957/49160: Author selected CC BY-NC
http://hdl.handle.net/1957/59717: Author didn’t respond — apply “all rights reserved”

**Comment by mwillihooper** [comment]
Heard back from Richard that his dept. doesn't do anything with the licensing fields. I fixed the three with CC licenses. Do we just delete dc.rights and dc.rights.uri fields for content with all rights reserved? Could @zhang4952 or @vantuyls point me to documentation or an example for that? Thanks!

**Comment by mwillihooper** [comment]
Talked to Steve and deleted dc.rights, dc.rights.uri, and license_rdf bistream to restore default on two remaining theses. Closing ticket
