### ISSUE TITLE
Define what the "default rights" uri is

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#40]
If an item in DSpace doesn't have a rights uri, then it will be issued a specific one. Which one? 

Related to #39

**Comment by vantuyls** [comment]
HA!

**Comment by mwillihooper** [comment]
I recommend this vague but accurate rights statement:  [http://rightsstatements.org/page/CNE/1.0/?language=en](http://rightsstatements.org/page/CNE/1.0/?language=en 
)
Rationale: Most ETDs are technically under copyright unless the author has chosen a CC license, which probably didn't happen for the historic ones. So we could slap "all rights reserved" on all of them, but that is potentially inaccurate for some and also maybe a little bit more chilling.
