### ISSUE TITLE
Mapping data with empty values

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#51]
Some ITEMs have metadata fields that are blank values. 

This happens on a wide range of different metadata, we need evaluate the value before running the mapping method.. Add Debug output? Fail on processing? Ignore the value?

These are the affected fields:

contributor.advisor
contributor.author
creator	
description	
description.abstract
description.sponsorship
language	
language.iso
publisher	
relation.ispartofseries
subject.lcsh
title	
degree.discipline
description.peerreview
description.peerreviewnotes
description.digitization
description.other
address

**Comment by mlv611** [comment]
I would ignore an empty field.  Is there any reason not to @mwillihooper and @vantuyls ?

**Comment by vantuyls** [comment]
blank fields are fine. presumably the dspace form will have forced user to enter information where required. 

is there any check to see that what you're getting out of dspace is what is actually in dspace with respect to metadata field contents? just checking to ensure that we know that there isn't supposed to be anything there...

**Comment by zhang4952** [comment]
Josh run a query and found there are total of ~240 items with blank value fields, he though the migration script should handle the case for robustness. And I just want to highlight two cases for discussion:
1. empty title: probably only one item and should we add it manually in DSpace?
2. dc.address: that is definitely incorrect, what about other similar fields? They may impact very few items but need decision: put all of them to additional_information if not empty, ignore them, or crosswalk to Hydra?

**Comment by mlv611** [comment]
This is more for @vantuyls or @mwillihooper

**Comment by vantuyls** [comment]
i'm not sure i fully understand what we're talking about here. but, to @zhang4952:
1. we should try to find the title on the item and add it manually in DSpace
2. what is dc.address?

**Comment by vantuyls** [comment]
ok, i think @revgum and i sorted this out. what i said up there ^ stands.

**Comment by revgum** [comment]
DSpace UI allows a user to "Add Metadata", without entering text or language fields.. and then save those blank metadata to the database. So, we'll write a general bit of code that allows for configuration to ignore these by default, but allow the configuration to halt/error on any specific mapped field that has an empty value. For instance, if an item has a blank `Title`, then it will fail to load into Hyrax anyhow..
