### ISSUE TITLE
[dspace collections] Map DSpace collection handle to name and Adminset

### ISSUE THREAD

**Issue by zhang4952** [osulp/dspace2hydra#61]
Create a method in lib/bag/bag.rb (?) with following functions:
- get the item collection_id from obect_properties hash: object_properties['ownerId'] and object_properties['otherIds'] 
- parse collection names from lookup file, such as lookup/collectionlist.csv (or YAML?)

**Comment by revgum** [comment]
Add the CSV and YAML parsing to `admin_set.rb` so that it knows how to read the lookup csv table and determine which admin_set_id should be used in place of the collection_handle for the ITEM that it is operating on. 

https://github.com/osulp/dspace2hydra/blob/master/mapping/admin_set.rb

**Comment by revgum** [comment]
closed per #78
