### ISSUE TITLE
[dspace collections] Map collection_name to metadata field

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#72]
This would be setup like a `custom_node` in the configuration, to take the value for the collection_handle and return the related collection_name from the CSV lookup table.

This should be contained in a new mapping class; `dspace_collection`

**Comment by revgum** [comment]
`item.rb`
- `#ownerId` this pulls the value from object.properties['ownerId']
- `#otherIds` this pulls the array of values from object.properties['otherIds'].split(',')
- `#collection_handles` this should return a flat array of the values : `[ownerId] + [otherIds]`


`custom_node` configuration: `value_from_node_property: collection_handles` would be used for both the collection names multi-value metadata, and the community names multi-value metadata. 

`custom_node` configuration `value_from_node_property: ownerId` would be used for the AdminSet lookup

**Comment by zhang4952** [comment]
What if collections ownerId and otherIds point to different AdminSet? For instance, if:
item 1957/57239
ownerId: 1957/43909 -> Faculty Article - OA Policy Implementation
otherIds: 1957/4 -> Default
then the AdminSet will be decided by 1957/43909 (ownerId) accordingly. @vantuyls @mwillihooper different thought?

**Comment by revgum** [comment]
fixed per #78
